version: "3.9"

services:

  client:
    build:
      context: client
      dockerfile: ./debug/Dockerfile
    image: reissjarvis/client
    restart: always
    volumes:
      - ./client:/usr/src/app
      - client_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'

  dog:
    build:
      context: dog-service
      dockerfile: ./debug/Dockerfile
    image: reissjarvis/dog-service
    restart: always
    volumes:
#      We add this volume for the file watcher to get updates inside the container
      - ./dog-service:/usr/src/app
    ports:
      - '8080:8080'

volumes:
  client_modules:
